/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Education = {
  _type: "education";
  schoolDirection?: string;
  schoolName?: string;
  schoolAddress?: AddressObject;
  duration?: DurationEducation;
};

export type DurationEducation = {
  _type: "durationEducation";
  start?: string;
  end?: string;
};

export type Exhibition = {
  _id: string;
  _type: "exhibition";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tagLine?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  date?: Duration;
  artist?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "person";
  }>;
  artwork?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "project";
  }>;
  poster?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  photos?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  gallery?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "gallery";
  };
};

export type Gallery = {
  _id: string;
  _type: "gallery";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tagLine?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  address?: AddressObject;
  contact?: ContactObjectNew;
};

export type Duration = {
  _type: "duration";
  start?: string;
  end?: string;
};

export type AddressObject = {
  _type: "addressObject";
  street?: string;
  number?: number;
  city?: string;
  postalCode?: string;
  country?: string;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  portrait?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  identity?: IdentityObject;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  address?: Array<
    {
      _key: string;
    } & AddressObject
  >;
  contact?: ContactObjectNew;
  education?: Array<
    {
      _key: string;
    } & Education
  >;
};

export type ContactObjectNew = {
  _type: "contactObjectNew";
  email?: string;
  phoneNumber?: string;
  mobileNumber?: string;
};

export type IdentityObject = {
  _type: "identityObject";
  firstName?: string;
  lastName?: string;
  gender?: "Male" | "Female" | "Other";
  birthDate?: string;
  birthPlace?: string;
};

export type SingletonTest = {
  _id: string;
  _type: "singletonTest";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  menuItems?: Array<
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "homepage";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      }
  >;
};

export type ContactObject = {
  _type: "contactObject";
  email?: string;
  phone?: string;
  mobile?: string;
  studio?: Array<{
    street?: string;
    postal?: string;
    city?: string;
    _type: "address";
    _key: string;
  }>;
};

export type Aboutpage = {
  _id: string;
  _type: "aboutpage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  contactObject?: Array<
    {
      _key: string;
    } & ContactObject
  >;
};

export type Contact = {
  _id: string;
  _type: "contact";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  phone?: string;
  mobile?: string;
  studio?: Array<{
    street?: string;
    postal?: string;
    city?: string;
    _type: "address";
    _key: string;
  }>;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  menuItems?: Array<
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "homepage";
      }
    | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "page";
      }
  >;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  seriesDescription?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  projects?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "project";
  }>;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  projectImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  projectTitle?: string;
  artist?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "person";
  }>;
  date?: string;
  material?: string;
  size?: {
    width?: string;
    height?: string;
  };
  soldStatus?: boolean;
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  homepageDescription?: string;
  homepageMainImage?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  homepageMainImageSingle?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  homepageCategories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  exhibitions?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "exhibition";
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityFileAsset
  | Geopoint
  | Education
  | DurationEducation
  | Exhibition
  | Gallery
  | Duration
  | AddressObject
  | Person
  | ContactObjectNew
  | IdentityObject
  | SingletonTest
  | ContactObject
  | Aboutpage
  | Contact
  | Settings
  | Page
  | Category
  | Project
  | Homepage
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homepage"][0]{  _id, homepageTitle,   "slug": slug.current,   homepageDescription,   // "homepageMainImage": homepageMainImage.asset->url,   homepageMainImage,  homepageMainImageSingle,  "homepageCategories": homepageCategories[]->{    _id,    name,     "slug": slug.current,    projects[0]->{projectImage, "projectImageDimensions": projectImage.asset->metadata.dimensions}  },  "homepageExpo": exhibitions[]->{  _id,  name,  poster,  "posterDimensions": poster.asset->metadata.dimensions,  description,  date,  gallery,  photos,  "images": photos[]{  asset->{  _id,  url,  metadata{ dimensions} }  },  "dimensions": photos[].asset->metadata.dimensions,  },}
export type HomePageQueryResult = {
  _id: string;
  homepageTitle: null;
  slug: string | null;
  homepageDescription: string | null;
  homepageMainImage: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  homepageMainImageSingle: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  homepageCategories: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    projects: {
      projectImage: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
      projectImageDimensions: SanityImageDimensions | null;
    } | null;
  }> | null;
  homepageExpo: Array<{
    _id: string;
    name: string | null;
    poster: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    posterDimensions: SanityImageDimensions | null;
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    date: Duration | null;
    gallery: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "gallery";
    } | null;
    photos: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }> | null;
    images: Array<{
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    }> | null;
    dimensions: Array<SanityImageDimensions | null> | null;
  }> | null;
} | null;
// Variable: homepageHeaderQuery
// Query: *[_type == "homepage"][0]{    "homepageMainImageAsset": homepageMainImageSingle.asset->metadata,     homepageMainImage,    homepageMainImageSingle,  }
export type HomepageHeaderQueryResult = {
  homepageMainImageAsset: SanityImageMetadata | null;
  homepageMainImage: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  homepageMainImageSingle: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
} | null;
// Variable: homePageSeriesQuery
// Query: *[_type == "homepage"][0]{    homepageCategories[]->{      _id,      name,       "slug": slug.current,      projects[0]->{      projectImage,       "projectImageDimensions": projectImage.asset->metadata.dimensions,       "projectImageMetadata": projectImage.asset->metadata,       "projectImagePalette": projectImage.asset->metadata.palette.darkVibrant.background}    }  }
export type HomePageSeriesQueryResult = {
  homepageCategories: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    projects: {
      projectImage: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
      projectImageDimensions: SanityImageDimensions | null;
      projectImageMetadata: SanityImageMetadata | null;
      projectImagePalette: string | null;
    } | null;
  }> | null;
} | null;
// Variable: homePageExhibitionQuery
// Query: *[_type == "homepage"][0]{      "homepageExpo": exhibitions[]->{      _id,      name,      poster,      "posterDimensions": poster.asset->metadata.dimensions,      description,      date,      gallery,      photos,      "images": photos[]{      asset,      "ref":asset._ref,      "imageDimensions":asset->metadata.dimensions      },      },    }
export type HomePageExhibitionQueryResult = {
  homepageExpo: Array<{
    _id: string;
    name: string | null;
    poster: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    posterDimensions: SanityImageDimensions | null;
    description: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    date: Duration | null;
    gallery: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "gallery";
    } | null;
    photos: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }> | null;
    images: Array<{
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      ref: string | null;
      imageDimensions: SanityImageDimensions | null;
    }> | null;
  }> | null;
} | null;
// Variable: projectsQuery
// Query: *[_type == "project"]   {_id,   "projectImage": projectImage.asset->url,    "projectImageDimensions": projectImage.asset->metadata.dimensions,   projectTitle,    projectDescription,    date,    material,    size,   soldStatus  }
export type ProjectsQueryResult = Array<{
  _id: string;
  projectImage: string | null;
  projectImageDimensions: SanityImageDimensions | null;
  projectTitle: string | null;
  projectDescription: null;
  date: string | null;
  material: string | null;
  size: {
    width?: string;
    height?: string;
  } | null;
  soldStatus: boolean | null;
}>;
// Variable: categoryQuery
// Query: *[_type == "category"]{  _id,   name,  seriesDescription,   "slug": slug.current,   "projects" : projects[]->{  _id,  "projectImage" : projectImage.asset->url,   "projectImageDimensions": projectImage.asset->metadata.dimensions,  projectTitle,  projectDescription,   date,   material,   size,  soldStatus  }}
export type CategoryQueryResult = Array<{
  _id: string;
  name: string | null;
  seriesDescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  slug: string | null;
  projects: Array<{
    _id: string;
    projectImage: string | null;
    projectImageDimensions: SanityImageDimensions | null;
    projectTitle: string | null;
    projectDescription: null;
    date: string | null;
    material: string | null;
    size: {
      width?: string;
      height?: string;
    } | null;
    soldStatus: boolean | null;
  }> | null;
}>;
// Variable: singleCategory
// Query: *[_type == "category" && slug.current == $slug][0]{  _id,   name,   seriesDescription,   "slug": slug.current,   "projects" : projects[]->{    _id,    "projectImage" : projectImage.asset->url,     "projectImageDimensions": projectImage.asset->metadata.dimensions,    projectTitle,    projectDescription,     date,     material,     size,    soldStatus  }}
export type SingleCategoryResult = {
  _id: string;
  name: string | null;
  seriesDescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  slug: string | null;
  projects: Array<{
    _id: string;
    projectImage: string | null;
    projectImageDimensions: SanityImageDimensions | null;
    projectTitle: string | null;
    projectDescription: null;
    date: string | null;
    material: string | null;
    size: {
      width?: string;
      height?: string;
    } | null;
    soldStatus: boolean | null;
  }> | null;
} | null;
// Variable: singleCategoryOrder
// Query: *[_type == "category" ] | order((slug.current match $slug) desc){  _id,   name,   seriesDescription,   "slug": slug.current,   "projects" : projects[]->{    _id,    "projectImage" : projectImage.asset->url,     "projectImageDimensions": projectImage.asset->metadata.dimensions,    projectTitle,    projectDescription,     date,     material,     size,    soldStatus  }}
export type SingleCategoryOrderResult = Array<{
  _id: string;
  name: string | null;
  seriesDescription: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  slug: string | null;
  projects: Array<{
    _id: string;
    projectImage: string | null;
    projectImageDimensions: SanityImageDimensions | null;
    projectTitle: string | null;
    projectDescription: null;
    date: string | null;
    material: string | null;
    size: {
      width?: string;
      height?: string;
    } | null;
    soldStatus: boolean | null;
  }> | null;
}>;
// Variable: aboutDavidQuery
// Query: *[_type == "person" && identity.firstName == "David" && identity.lastName == "van Loon"][0]{_id, identity, description, portrait, educationText}
export type AboutDavidQueryResult = {
  _id: string;
  identity: IdentityObject | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  portrait: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  educationText: null;
} | null;
// Variable: bioDavidQuery
// Query: *[_type == "person" && identity.firstName == "David" && identity.lastName == "van Loon"][0]{  _id, description, portrait, "dimensions":portrait.asset->metadata.dimensions}
export type BioDavidQueryResult = {
  _id: string;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  portrait: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  dimensions: SanityImageDimensions | null;
} | null;
// Variable: contactDavidQuery
// Query: *[_type == "person" && identity.firstName == "David" && identity.lastName == "van Loon"][0]{_id, contact, address}
export type ContactDavidQueryResult = {
  _id: string;
  contact: ContactObjectNew | null;
  address: Array<
    {
      _key: string;
    } & AddressObject
  > | null;
} | null;
// Variable: educationDavidQuery
// Query: *[_type == "person" && identity.firstName == "David" && identity.lastName == "van Loon"][0]{_id, educationText}
export type EducationDavidQueryResult = {
  _id: string;
  educationText: null;
} | null;
// Variable: educationDavidQueryAlt
// Query: *[_type == "person" && identity.firstName == "David" && identity.lastName == "van Loon"][0]{_id, "education": education[]{duration, schoolDirection, schoolName, schoolAddress}}
export type EducationDavidQueryAltResult = {
  _id: string;
  education: Array<{
    duration: DurationEducation | null;
    schoolDirection: string | null;
    schoolName: string | null;
    schoolAddress: AddressObject | null;
  }> | null;
} | null;
// Variable: exhibitionDavidQuery
// Query: *[_type == "exhibition" && artist[]->identity.firstName match "David" && artist[]->identity.lastName match "van Loon"][]{_id, date, name, gallery->{name, address}, tagline, description}
export type ExhibitionDavidQueryResult = Array<never>;
// Variable: exhibitionWithoutFilterQuery
// Query: *[_type == "exhibition"][]{_id, date, name, gallery->{name, address}, tagline, description}
export type ExhibitionWithoutFilterQueryResult = Array<{
  _id: string;
  date: Duration | null;
  name: string | null;
  gallery: {
    name: string | null;
    address: AddressObject | null;
  } | null;
  tagline: null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
}>;
// Variable: pagesQuery
// Query: *[_type == "page"]{  _id,   title,   "slug":slug.current,   content}
export type PagesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
}>;
// Variable: pageQuery
// Query: *[_type == "page" && slug.current == $slug][0]{  _id,   title,   "slug":slug.current,   content}
export type PageQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;
// Variable: settingsQuery
// Query: *[_type == "settings"][0]{  menuItems[]->{_type, "slug": slug.current, title}}
export type SettingsQueryResult = {
  menuItems: Array<
    | {
        _type: "homepage";
        slug: string | null;
        title: string | null;
      }
    | {
        _type: "page";
        slug: string | null;
        title: string | null;
      }
  > | null;
} | null;
// Variable: testQuery
// Query: *[_type == "settingsTest"]{    menuItems[]->{      homepageTitle, title    }  }
export type TestQueryResult = Array<never>;
// Variable: homepageTestQuery
// Query: *[_type == "homepage"][0]{  _id, homepageTitle,   "slug": slug.current,   homepageDescription,   // "homepageMainImage": homepageMainImage.asset->url,   homepageMainImage,  homepageMainImageSingle,  "homepageCategories": homepageCategories[]->{    name,     "slug": slug.current,    projects[0]->{projectImage, "projectImageDimensions": projectImage.asset->metadata.dimensions}  }}
export type HomepageTestQueryResult = {
  _id: string;
  homepageTitle: null;
  slug: string | null;
  homepageDescription: string | null;
  homepageMainImage: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  homepageMainImageSingle: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  homepageCategories: Array<{
    name: string | null;
    slug: string | null;
    projects: {
      projectImage: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
      projectImageDimensions: SanityImageDimensions | null;
    } | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n*[_type == "homepage"][0]{\n  _id, homepageTitle, \n  "slug": slug.current, \n  homepageDescription, \n  // "homepageMainImage": homepageMainImage.asset->url, \n  homepageMainImage,\n  homepageMainImageSingle,\n  "homepageCategories": homepageCategories[]->{\n    _id,\n    name, \n    "slug": slug.current,\n    projects[0]->{projectImage, "projectImageDimensions": projectImage.asset->metadata.dimensions}\n  },\n  "homepageExpo": exhibitions[]->{\n  _id,\n  name,\n  poster,\n  "posterDimensions": poster.asset->metadata.dimensions,\n  description,\n  date,\n  gallery,\n  photos,\n  "images": photos[]{\n  asset->{\n  _id,\n  url,\n  metadata{ dimensions} }\n  },\n  "dimensions": photos[].asset->metadata.dimensions,\n  },\n}': HomePageQueryResult;
    '\n  *[_type == "homepage"][0]{\n    "homepageMainImageAsset": homepageMainImageSingle.asset->metadata, \n    homepageMainImage,\n    homepageMainImageSingle,\n  }': HomepageHeaderQueryResult;
    '\n  *[_type == "homepage"][0]{\n    homepageCategories[]->{\n      _id,\n      name, \n      "slug": slug.current,\n      projects[0]->{\n      projectImage, \n      "projectImageDimensions": projectImage.asset->metadata.dimensions, \n      "projectImageMetadata": projectImage.asset->metadata, \n      "projectImagePalette": projectImage.asset->metadata.palette.darkVibrant.background}\n    }\n  }': HomePageSeriesQueryResult;
    '\n    *[_type == "homepage"][0]{\n      "homepageExpo": exhibitions[]->{\n      _id,\n      name,\n      poster,\n      "posterDimensions": poster.asset->metadata.dimensions,\n      description,\n      date,\n      gallery,\n      photos,\n      "images": photos[]{\n      asset,\n      "ref":asset._ref,\n      "imageDimensions":asset->metadata.dimensions\n      },\n      },\n    }': HomePageExhibitionQueryResult;
    '\n*[_type == "project"]\n   {_id,\n   "projectImage": projectImage.asset->url, \n   "projectImageDimensions": projectImage.asset->metadata.dimensions,\n   projectTitle, \n   projectDescription, \n   date, \n   material, \n   size,\n   soldStatus\n  }': ProjectsQueryResult;
    '\n*[_type == "category"]{\n  _id, \n  name,\n  seriesDescription, \n  "slug": slug.current, \n  "projects" : projects[]->{\n  _id,\n  "projectImage" : projectImage.asset->url, \n  "projectImageDimensions": projectImage.asset->metadata.dimensions,\n  projectTitle,\n  projectDescription, \n  date, \n  material, \n  size,\n  soldStatus\n  }\n}': CategoryQueryResult;
    '\n*[_type == "category" && slug.current == $slug][0]{\n  _id, \n  name, \n  seriesDescription, \n  "slug": slug.current, \n  "projects" : projects[]->{\n    _id,\n    "projectImage" : projectImage.asset->url, \n    "projectImageDimensions": projectImage.asset->metadata.dimensions,\n    projectTitle,\n    projectDescription, \n    date, \n    material, \n    size,\n    soldStatus\n  }\n}': SingleCategoryResult;
    '\n*[_type == "category" ] | order((slug.current match $slug) desc){\n  _id, \n  name, \n  seriesDescription, \n  "slug": slug.current, \n  "projects" : projects[]->{\n    _id,\n    "projectImage" : projectImage.asset->url, \n    "projectImageDimensions": projectImage.asset->metadata.dimensions,\n    projectTitle,\n    projectDescription, \n    date, \n    material, \n    size,\n    soldStatus\n  }\n}': SingleCategoryOrderResult;
    '*[_type == "person" && identity.firstName == "David" && identity.lastName == "van Loon"][0]{_id, identity, description, portrait, educationText}': AboutDavidQueryResult;
    '*[_type == "person" && identity.firstName == "David" && identity.lastName == "van Loon"][0]{\n  _id, description, portrait, "dimensions":portrait.asset->metadata.dimensions}': BioDavidQueryResult;
    '*[_type == "person" && identity.firstName == "David" && identity.lastName == "van Loon"][0]{_id, contact, address}': ContactDavidQueryResult;
    '*[_type == "person" && identity.firstName == "David" && identity.lastName == "van Loon"][0]{_id, educationText}': EducationDavidQueryResult;
    '*[_type == "person" && identity.firstName == "David" && identity.lastName == "van Loon"][0]{_id, "education": education[]{duration, schoolDirection, schoolName, schoolAddress}}': EducationDavidQueryAltResult;
    '*[_type == "exhibition" && artist[]->identity.firstName match "David" && artist[]->identity.lastName match "van Loon"][]{_id, date, name, gallery->{name, address}, tagline, description}': ExhibitionDavidQueryResult;
    '*[_type == "exhibition"][]{_id, date, name, gallery->{name, address}, tagline, description}': ExhibitionWithoutFilterQueryResult;
    '\n*[_type == "page"]{\n  _id, \n  title, \n  "slug":slug.current, \n  content\n}': PagesQueryResult;
    '\n*[_type == "page" && slug.current == $slug][0]{\n  _id, \n  title, \n  "slug":slug.current, \n  content\n}': PageQueryResult;
    '\n*[_type == "settings"][0]{\n  menuItems[]->{_type, "slug": slug.current, title}\n}': SettingsQueryResult;
    '\n  *[_type == "settingsTest"]{\n    menuItems[]->{\n      homepageTitle, title\n    }\n  }\n': TestQueryResult;
    '\n*[_type == "homepage"][0]{\n  _id, homepageTitle, \n  "slug": slug.current, \n  homepageDescription, \n  // "homepageMainImage": homepageMainImage.asset->url, \n  homepageMainImage,\n  homepageMainImageSingle,\n  "homepageCategories": homepageCategories[]->{\n    name, \n    "slug": slug.current,\n    projects[0]->{projectImage, "projectImageDimensions": projectImage.asset->metadata.dimensions}\n  }\n}': HomepageTestQueryResult;
  }
}
