import { Analytics } from "@vercel/analytics/react";

import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { DM_Sans } from "next/font/google";

import "../globals.css";
import NavBar from "@/components/global/navigation/navbar";
import Footer from "@/components/global/footer";
import NavbarContainer from "@/components/global/navigation/navbar-container";
import NavbarWrapper from "@/components/global/navigation/navbar-wrapper";

// const Inter = Inter({ subsets: ["latin"], display: "swap" });

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  // style: ["normal", "italic"],
  display: "swap",
  variable: "--font-montserrat",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-dmSans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={dmSans.variable}>
      <body className={`overflow-x-hidden bg-gray-100 tracking-tight`}>
        {/* <body className={inter.className}> */}
        <>
          <NavbarWrapper />
          {children}
          <Analytics />
          <Footer />
        </>
      </body>
    </html>
  );
}
