import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { DM_Sans } from "next/font/google";
import { Golos_Text } from "next/font/google";
import { Public_Sans } from "next/font/google";

import "./globals.css";

// const Inter = Inter({ subsets: ["latin"], display: "swap" });

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  // style: ["normal", "italic"],
  display: "swap",
  variable: "--font-montserrat",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-dmSans",
});

const golosText = Golos_Text({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
  variable: "--font-golosText",
});

const publicSans = Public_Sans({
  subsets: ["latin"],
  weight: ["400", "500"],
  display: "swap",
  variable: "--font-publicSans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${publicSans.variable} ${golosText.variable}`}>
      <body className="font-publicSans mx-auto mt-0 min-h-screen bg-gray-50">
        {children}
      </body>
    </html>
  );
}
